### ISSUE TITLE
Add to Fuzzbench

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL-legacy#17]
This is a longer-reaching issue:
We should eventually add LibAFL to Fuzzbench, potentially even the in-mem fuzzer (crushing all other fuzzers :) ).

**Comment by vanhauser-thc** [comment]
what is needed for that?
The targets are libffuzer harnesses, so if we create a generic main.c that calls the libafl around llvmtestoneinput it would be ready to go from that side.

the question is though - what is needed in libafl for that?

fuzzbench fuzzer need:
  * writing new queue items into a directory (like out/queue)
  * read and use seeds (like seeds/* ...)
  * mutate input :-)
  * don't crash :-)
  * optional: use a afl-style dictionary

so what is not there yet?

**Comment by domenukk** [comment]
The wrapper for libfuzzer to in-mem-executor, proper afl-like outputs, and later dict support, are missing.
As all of the testcases are not crashing, we don't have a problem there (yet), hooray for lab environments.

**Comment by domenukk** [comment]
First run done
