### ISSUE TITLE
In-Mem Crash Recovery

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL-legacy#18]
Right now, a Crashing input in the In-Memory Fuzzer will be lost.
This is rather unfortunate. As we use shared maps/llmp for fuzzing, the input is still around after a crash, and a new process, or even the broker, should be able to recover it.

**Comment by vanhauser-thc** [comment]
In memory should still be forked off and then the crash can a) be detected and b) input recovered. and c) respawn and continue.

**Comment by rish9101** [comment]
How about a SEGV(and other possible crashes) signal handler that send the message and maybe `longjumps` back to the looping part. So we don't have to respawn the instance.

**Comment by vanhauser-thc** [comment]
That can fail because needed memory structures might have been overwritten. That unlikely though possible.

**Comment by andreafioraldi** [comment]
This may work with snapshot, not with persistent. My 2c is that the monitor will respawn a new fuzzer.

**Comment by domenukk** [comment]
One Problem I see: in the current LLMP, there can be a race condition on EOP (end of page) where the new shared map has not yet been  mapped by the broker. A crash in this (unlikely) scenario would mean the sharedmap gets reference counted to 0 and removed, we have no way to read it anymore.
Just putting this out there, there are solutions of course

**Comment by andreafioraldi** [comment]
Can't you use a signal handler to do cleanup and then let the target crash?

**Comment by domenukk** [comment]
Well the 'cleanup' would be to block until something else mapps the page?

**Comment by domenukk** [comment]
Hm actually this is not such a bad idea: simply spinlock on `save_to_unmap`
https://github.com/AFLplusplus/LibAFL/blob/387a1665b4f7ef921589e30976ce54b39d70023f/src/llmp.c#L600

**Comment by domenukk** [comment]
The libaflfuzzer client catches signals, notifies the broker, spinlock waits for the broker, exits. The broker then respawns this client.
