### ISSUE TITLE
Libfuzzer Compatible Wrapper for In-Mem Fuzzer

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL-legacy#23]
We should add a in-mem fuzzer example that is compatible to LibFuzzer Testcases out of the box.
That makes LibFuzzer more versatile and will be needed for #17

**Comment by vanhauser-thc** [comment]
Mostly done - needs two more things:

1. I need to initialize targets in their fuzzing threads. where? It must be done once in each thread.

2. the reset of the coverage map may not be in the harness function. this must be done in the library

then it is finished. the other stuff is working fine already.
when the two items are completed it is ready for fuzzbench.

**Comment by rish9101** [comment]
I've added both of these in [this](https://github.com/AFLplusplus/LibAFL/commit/8d3986188bacf656d2587e8eb4c4260b8c9f5ff5) commit now.

**Comment by domenukk** [comment]
Done with libaflfuzzer
