### ISSUE TITLE
Bind to CPU

### ISSUE THREAD

**Issue by domenukk** [AFLplusplus/LibAFL-legacy#26]
The current LibAFL does not bind to CPU cores, however, this should be part of the lib:
https://github.com/AFLplusplus/AFLplusplus/blob/7f621509eee57f0b6fd9ad542adc4f2acafeb059/src/afl-fuzz-init.c#L109

**Comment by vanhauser-thc** [comment]
as this gives a huge performance increase - yes, yes and yes.

**Comment by rish9101** [comment]
I've started working on this over here. https://github.com/AFLplusplus/LibAFL/tree/bind_to_cpu

**Comment by domenukk** [comment]
nice!
One thing though I don't see a reason to making the actual bind functions depending on the engine, right? Maybe instead return the bound cpu index, or -1 on error?

**Comment by rish9101** [comment]
I was thinking over something, about storing the bound cpu in `engine` somewhere. So that when we restart the engine we can possibly bind it again to that cpu? What do you think?

**Comment by rish9101** [comment]
Btw @domenukk  any chance of any race condition during cpu binding? two instances being bound to the same cpu?

**Comment by domenukk** [comment]
> I was thinking over something, about storing the bound cpu in `engine` somewhere. So that when we restart the engine we can possibly bind it again to that cpu? What do you think?

That is possible without taking an engine pointer. The caller can call bindcpu the first time around, and bind to a speciific cpu the second time.



> Btw @domenukk any chance of any race condition during cpu binding? two instances being bound to the same cpu?

Original afl had a race condition here, but I think @vanhauser-thc fixed it at some point(?)

**Comment by domenukk** [comment]
Done with #42
